{"uuid": "d4b19dea-c7ff-444a-9abe-7e0ebafe621c", "children": ["1b137956-bc74-4656-9c6b-75adae0ca694"], "befores": [{"name": "_xunit_setup_method_fixture_TestSet", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"e:\\test_huahua\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"E:\\test_huahua\\testcase\\test_set.py\", line 6, in setup\n    self.set = App().start().main().goto_set()\n  File \"E:\\test_huahua\\page\\app.py\", line 69, in main\n    WebDriverWait(self._driver, 60).until(wait_load)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1703237959969, "stop": 1703238030926}], "start": 1703237959969, "stop": 1703238030935}